// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/coordinator.proto

package coordinatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorType int32

const (
	ErrorType_OK                ErrorType = 0
	ErrorType_UNKNOWN           ErrorType = 1
	ErrorType_NO_NODE           ErrorType = 2
	ErrorType_NO_PV             ErrorType = 3
	ErrorType_INTERNAL_ERROR    ErrorType = 4
	ErrorType_INVALID_PARAMETER ErrorType = 5
)

var ErrorType_name = map[int32]string{
	0: "OK",
	1: "UNKNOWN",
	2: "NO_NODE",
	3: "NO_PV",
	4: "INTERNAL_ERROR",
	5: "INVALID_PARAMETER",
}

var ErrorType_value = map[string]int32{
	"OK":                0,
	"UNKNOWN":           1,
	"NO_NODE":           2,
	"NO_PV":             3,
	"INTERNAL_ERROR":    4,
	"INVALID_PARAMETER": 5,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{0}
}

type StorageType int32

const (
	StorageType_STORAGE StorageType = 0
	StorageType_LIMIT   StorageType = 1
)

var StorageType_name = map[int32]string{
	0: "STORAGE",
	1: "LIMIT",
}

var StorageType_value = map[string]int32{
	"STORAGE": 0,
	"LIMIT":   1,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}

func (StorageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{1}
}

type Unit int32

const (
	Unit_B  Unit = 0
	Unit_KB Unit = 1
	Unit_MB Unit = 2
	Unit_GB Unit = 3
	Unit_C  Unit = 4
)

var Unit_name = map[int32]string{
	0: "B",
	1: "KB",
	2: "MB",
	3: "GB",
	4: "C",
}

var Unit_value = map[string]int32{
	"B":  0,
	"KB": 1,
	"MB": 2,
	"GB": 3,
	"C":  4,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}

func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{2}
}

type StorageLevel int32

const (
	StorageLevel_HDD StorageLevel = 0
	StorageLevel_SSD StorageLevel = 1
	StorageLevel_NVM StorageLevel = 2
)

var StorageLevel_name = map[int32]string{
	0: "HDD",
	1: "SSD",
	2: "NVM",
}

var StorageLevel_value = map[string]int32{
	"HDD": 0,
	"SSD": 1,
	"NVM": 2,
}

func (x StorageLevel) String() string {
	return proto.EnumName(StorageLevel_name, int32(x))
}

func (StorageLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{3}
}

type RequestHeader struct {
	// the node id of the sender
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type ResponseHeader struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{1}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ResponseHeader) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Type                 ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=coordinatorpb.ErrorType" json:"type,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_OK
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Resource struct {
	Type                 StorageType `protobuf:"varint,1,opt,name=type,proto3,enum=coordinatorpb.StorageType" json:"type,omitempty"`
	Kind                 string      `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Size                 uint64      `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Unit                 Unit        `protobuf:"varint,4,opt,name=unit,proto3,enum=coordinatorpb.Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{3}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() StorageType {
	if m != nil {
		return m.Type
	}
	return StorageType_STORAGE
}

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Resource) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Resource) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_B
}

type PVC struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resource             []*Resource `protobuf:"bytes,2,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PVC) Reset()         { *m = PVC{} }
func (m *PVC) String() string { return proto.CompactTextString(m) }
func (*PVC) ProtoMessage()    {}
func (*PVC) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{4}
}

func (m *PVC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVC.Unmarshal(m, b)
}
func (m *PVC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVC.Marshal(b, m, deterministic)
}
func (m *PVC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVC.Merge(m, src)
}
func (m *PVC) XXX_Size() int {
	return xxx_messageInfo_PVC.Size(m)
}
func (m *PVC) XXX_DiscardUnknown() {
	xxx_messageInfo_PVC.DiscardUnknown(m)
}

var xxx_messageInfo_PVC proto.InternalMessageInfo

func (m *PVC) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PVC) GetResource() []*Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type PutPodResourceRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string         `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pvc                  []*PVC         `protobuf:"bytes,4,rep,name=pvc,proto3" json:"pvc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutPodResourceRequest) Reset()         { *m = PutPodResourceRequest{} }
func (m *PutPodResourceRequest) String() string { return proto.CompactTextString(m) }
func (*PutPodResourceRequest) ProtoMessage()    {}
func (*PutPodResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{5}
}

func (m *PutPodResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPodResourceRequest.Unmarshal(m, b)
}
func (m *PutPodResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPodResourceRequest.Marshal(b, m, deterministic)
}
func (m *PutPodResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPodResourceRequest.Merge(m, src)
}
func (m *PutPodResourceRequest) XXX_Size() int {
	return xxx_messageInfo_PutPodResourceRequest.Size(m)
}
func (m *PutPodResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPodResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPodResourceRequest proto.InternalMessageInfo

func (m *PutPodResourceRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PutPodResourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PutPodResourceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PutPodResourceRequest) GetPvc() []*PVC {
	if m != nil {
		return m.Pvc
	}
	return nil
}

type PutPodResourceResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutPodResourceResponse) Reset()         { *m = PutPodResourceResponse{} }
func (m *PutPodResourceResponse) String() string { return proto.CompactTextString(m) }
func (*PutPodResourceResponse) ProtoMessage()    {}
func (*PutPodResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{6}
}

func (m *PutPodResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPodResourceResponse.Unmarshal(m, b)
}
func (m *PutPodResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPodResourceResponse.Marshal(b, m, deterministic)
}
func (m *PutPodResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPodResourceResponse.Merge(m, src)
}
func (m *PutPodResourceResponse) XXX_Size() int {
	return xxx_messageInfo_PutPodResourceResponse.Size(m)
}
func (m *PutPodResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPodResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutPodResourceResponse proto.InternalMessageInfo

func (m *PutPodResourceResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type Storage struct {
	Node                 string       `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                StorageLevel `protobuf:"varint,3,opt,name=level,proto3,enum=coordinatorpb.StorageLevel" json:"level,omitempty"`
	Resource             []*Resource  `protobuf:"bytes,4,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{7}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Storage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storage) GetLevel() StorageLevel {
	if m != nil {
		return m.Level
	}
	return StorageLevel_HDD
}

func (m *Storage) GetResource() []*Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type PutNodeResourceRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Storage              []*Storage     `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutNodeResourceRequest) Reset()         { *m = PutNodeResourceRequest{} }
func (m *PutNodeResourceRequest) String() string { return proto.CompactTextString(m) }
func (*PutNodeResourceRequest) ProtoMessage()    {}
func (*PutNodeResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{8}
}

func (m *PutNodeResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutNodeResourceRequest.Unmarshal(m, b)
}
func (m *PutNodeResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutNodeResourceRequest.Marshal(b, m, deterministic)
}
func (m *PutNodeResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutNodeResourceRequest.Merge(m, src)
}
func (m *PutNodeResourceRequest) XXX_Size() int {
	return xxx_messageInfo_PutNodeResourceRequest.Size(m)
}
func (m *PutNodeResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutNodeResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutNodeResourceRequest proto.InternalMessageInfo

func (m *PutNodeResourceRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PutNodeResourceRequest) GetStorage() []*Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

type PutNodeResourceResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutNodeResourceResponse) Reset()         { *m = PutNodeResourceResponse{} }
func (m *PutNodeResourceResponse) String() string { return proto.CompactTextString(m) }
func (*PutNodeResourceResponse) ProtoMessage()    {}
func (*PutNodeResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{9}
}

func (m *PutNodeResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutNodeResourceResponse.Unmarshal(m, b)
}
func (m *PutNodeResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutNodeResourceResponse.Marshal(b, m, deterministic)
}
func (m *PutNodeResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutNodeResourceResponse.Merge(m, src)
}
func (m *PutNodeResourceResponse) XXX_Size() int {
	return xxx_messageInfo_PutNodeResourceResponse.Size(m)
}
func (m *PutNodeResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutNodeResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutNodeResourceResponse proto.InternalMessageInfo

func (m *PutNodeResourceResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// return all the node's resource or one node resource
// if header.node_id = "all",then return all
type GetNodeResourceRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetNodeResourceRequest) Reset()         { *m = GetNodeResourceRequest{} }
func (m *GetNodeResourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeResourceRequest) ProtoMessage()    {}
func (*GetNodeResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{10}
}

func (m *GetNodeResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeResourceRequest.Unmarshal(m, b)
}
func (m *GetNodeResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeResourceRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeResourceRequest.Merge(m, src)
}
func (m *GetNodeResourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeResourceRequest.Size(m)
}
func (m *GetNodeResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeResourceRequest proto.InternalMessageInfo

func (m *GetNodeResourceRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetNodeResourceResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Storage              []*Storage      `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetNodeResourceResponse) Reset()         { *m = GetNodeResourceResponse{} }
func (m *GetNodeResourceResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeResourceResponse) ProtoMessage()    {}
func (*GetNodeResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{11}
}

func (m *GetNodeResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeResourceResponse.Unmarshal(m, b)
}
func (m *GetNodeResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeResourceResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeResourceResponse.Merge(m, src)
}
func (m *GetNodeResourceResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeResourceResponse.Size(m)
}
func (m *GetNodeResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeResourceResponse proto.InternalMessageInfo

func (m *GetNodeResourceResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetNodeResourceResponse) GetStorage() []*Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

// TODO
// don't know is it need volumegroup
type Device struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Maj                  uint64   `protobuf:"varint,2,opt,name=maj,proto3" json:"maj,omitempty"`
	Min                  uint64   `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Vg                   string   `protobuf:"bytes,6,opt,name=vg,proto3" json:"vg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{12}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetMaj() uint64 {
	if m != nil {
		return m.Maj
	}
	return 0
}

func (m *Device) GetMin() uint64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Device) GetVg() string {
	if m != nil {
		return m.Vg
	}
	return ""
}

type PutPVRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Device               *Device        `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutPVRequest) Reset()         { *m = PutPVRequest{} }
func (m *PutPVRequest) String() string { return proto.CompactTextString(m) }
func (*PutPVRequest) ProtoMessage()    {}
func (*PutPVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{13}
}

func (m *PutPVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPVRequest.Unmarshal(m, b)
}
func (m *PutPVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPVRequest.Marshal(b, m, deterministic)
}
func (m *PutPVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPVRequest.Merge(m, src)
}
func (m *PutPVRequest) XXX_Size() int {
	return xxx_messageInfo_PutPVRequest.Size(m)
}
func (m *PutPVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPVRequest proto.InternalMessageInfo

func (m *PutPVRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PutPVRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PutPVRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

// return if it is ok
type PutPVResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutPVResponse) Reset()         { *m = PutPVResponse{} }
func (m *PutPVResponse) String() string { return proto.CompactTextString(m) }
func (*PutPVResponse) ProtoMessage()    {}
func (*PutPVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe1575f6d8e2596, []int{14}
}

func (m *PutPVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPVResponse.Unmarshal(m, b)
}
func (m *PutPVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPVResponse.Marshal(b, m, deterministic)
}
func (m *PutPVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPVResponse.Merge(m, src)
}
func (m *PutPVResponse) XXX_Size() int {
	return xxx_messageInfo_PutPVResponse.Size(m)
}
func (m *PutPVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutPVResponse proto.InternalMessageInfo

func (m *PutPVResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterEnum("coordinatorpb.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterEnum("coordinatorpb.StorageType", StorageType_name, StorageType_value)
	proto.RegisterEnum("coordinatorpb.Unit", Unit_name, Unit_value)
	proto.RegisterEnum("coordinatorpb.StorageLevel", StorageLevel_name, StorageLevel_value)
	proto.RegisterType((*RequestHeader)(nil), "coordinatorpb.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "coordinatorpb.ResponseHeader")
	proto.RegisterType((*Error)(nil), "coordinatorpb.Error")
	proto.RegisterType((*Resource)(nil), "coordinatorpb.Resource")
	proto.RegisterType((*PVC)(nil), "coordinatorpb.PVC")
	proto.RegisterType((*PutPodResourceRequest)(nil), "coordinatorpb.PutPodResourceRequest")
	proto.RegisterType((*PutPodResourceResponse)(nil), "coordinatorpb.PutPodResourceResponse")
	proto.RegisterType((*Storage)(nil), "coordinatorpb.Storage")
	proto.RegisterType((*PutNodeResourceRequest)(nil), "coordinatorpb.PutNodeResourceRequest")
	proto.RegisterType((*PutNodeResourceResponse)(nil), "coordinatorpb.PutNodeResourceResponse")
	proto.RegisterType((*GetNodeResourceRequest)(nil), "coordinatorpb.GetNodeResourceRequest")
	proto.RegisterType((*GetNodeResourceResponse)(nil), "coordinatorpb.GetNodeResourceResponse")
	proto.RegisterType((*Device)(nil), "coordinatorpb.Device")
	proto.RegisterType((*PutPVRequest)(nil), "coordinatorpb.PutPVRequest")
	proto.RegisterType((*PutPVResponse)(nil), "coordinatorpb.PutPVResponse")
}

func init() { proto.RegisterFile("proto/coordinator.proto", fileDescriptor_fbe1575f6d8e2596) }

var fileDescriptor_fbe1575f6d8e2596 = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x72, 0xc2, 0x44,
	0x18, 0x26, 0x27, 0x28, 0x3f, 0x2d, 0xae, 0xab, 0x2d, 0x19, 0x5a, 0x67, 0x98, 0x4c, 0xab, 0xc8,
	0x54, 0x54, 0xaa, 0x0f, 0xc0, 0xc9, 0x96, 0x29, 0x24, 0xcc, 0x42, 0xf1, 0xca, 0xc1, 0x94, 0xec,
	0xd0, 0x68, 0x9b, 0xc4, 0x24, 0x30, 0x53, 0xaf, 0x1c, 0x6f, 0xbc, 0xf0, 0x09, 0x7c, 0x00, 0xdf,
	0xd0, 0x07, 0x70, 0x76, 0x13, 0x4e, 0x21, 0x4e, 0x3b, 0xb6, 0x57, 0xf9, 0x77, 0xf7, 0xe3, 0xfb,
	0xbf, 0xff, 0x38, 0x40, 0xc9, 0xf3, 0xdd, 0xd0, 0xfd, 0x72, 0xe6, 0xba, 0xbe, 0x65, 0x3b, 0x66,
	0xe8, 0xfa, 0x75, 0x7e, 0x83, 0x8f, 0xb6, 0xae, 0xbc, 0x7b, 0xad, 0x0a, 0x47, 0x84, 0xfe, 0xb2,
	0xa0, 0x41, 0x78, 0x43, 0x4d, 0x8b, 0xfa, 0xb8, 0x04, 0x39, 0xc7, 0xb5, 0xe8, 0xd4, 0xb6, 0x54,
	0xa1, 0x22, 0x54, 0xf3, 0x24, 0xcb, 0x8e, 0x3d, 0x4b, 0xbb, 0x83, 0x22, 0xa1, 0x81, 0xe7, 0x3a,
	0x01, 0x7d, 0x01, 0x8a, 0x6b, 0xa0, 0x50, 0xdf, 0x77, 0x7d, 0x55, 0xac, 0x08, 0xd5, 0x42, 0xe3,
	0xe3, 0xfa, 0x8e, 0xcf, 0x7a, 0x97, 0xbd, 0x91, 0x08, 0xa2, 0x19, 0xa0, 0xf0, 0x33, 0xbe, 0x04,
	0x39, 0x7c, 0xf6, 0x28, 0xa7, 0x2a, 0x36, 0xd4, 0xb4, 0xdf, 0x8c, 0x9f, 0x3d, 0x4a, 0x38, 0x0a,
	0xab, 0x90, 0x7b, 0xa2, 0x41, 0x60, 0xce, 0x29, 0x77, 0x92, 0x27, 0xab, 0xa3, 0xf6, 0xa7, 0x00,
	0x07, 0x84, 0x06, 0xee, 0xc2, 0x9f, 0x51, 0x5c, 0xdf, 0x21, 0x2d, 0x27, 0x48, 0x47, 0xa1, 0xeb,
	0x9b, 0x73, 0xba, 0x45, 0x8b, 0x41, 0xfe, 0xd9, 0x76, 0xac, 0x98, 0x93, 0xdb, 0xec, 0x2e, 0xb0,
	0x7f, 0xa5, 0xaa, 0x54, 0x11, 0xaa, 0x32, 0xe1, 0x36, 0xfe, 0x0c, 0xe4, 0x85, 0x63, 0x87, 0xaa,
	0xcc, 0x79, 0x3f, 0x4a, 0xf0, 0xde, 0x39, 0x76, 0x48, 0x38, 0x40, 0xd3, 0x41, 0x1a, 0x4e, 0xda,
	0x8c, 0xc3, 0x31, 0x9f, 0x68, 0x9c, 0x27, 0x6e, 0xe3, 0x2b, 0x38, 0xf0, 0x63, 0x9d, 0xaa, 0x58,
	0x91, 0xaa, 0x85, 0x46, 0x29, 0xc1, 0xb3, 0x0a, 0x83, 0xac, 0x81, 0xda, 0xdf, 0x02, 0x1c, 0x0f,
	0x17, 0xe1, 0xd0, 0xb5, 0xd6, 0x8f, 0x51, 0xf9, 0xf0, 0x37, 0x90, 0x7d, 0xe0, 0x75, 0xe1, 0x4e,
	0x0a, 0x8d, 0xb3, 0x3d, 0xb2, 0xad, 0x32, 0x93, 0x18, 0xbb, 0x16, 0x26, 0x6e, 0x09, 0x3b, 0x83,
	0x3c, 0xfb, 0x06, 0x9e, 0x39, 0x8b, 0xa2, 0xce, 0x93, 0xcd, 0x05, 0x3e, 0x07, 0xc9, 0x5b, 0xce,
	0x54, 0x99, 0x2b, 0xc6, 0x09, 0x27, 0xc3, 0x49, 0x9b, 0xb0, 0x67, 0xcd, 0x80, 0x93, 0xa4, 0xcc,
	0xa8, 0x77, 0xf0, 0xb7, 0x09, 0x9d, 0x9f, 0xec, 0x07, 0xbd, 0xd5, 0x64, 0x2b, 0xa1, 0xda, 0x5f,
	0x02, 0xe4, 0xe2, 0x7a, 0x71, 0xd1, 0xae, 0xb5, 0xc9, 0xa6, 0x6b, 0xd1, 0xd4, 0x40, 0xbe, 0x06,
	0xe5, 0x91, 0x2e, 0xe9, 0x23, 0x0f, 0xa2, 0xd8, 0x38, 0x4d, 0x2f, 0x7f, 0x9f, 0x41, 0x48, 0x84,
	0xdc, 0x29, 0x8a, 0xfc, 0xda, 0xa2, 0xfc, 0x26, 0xf0, 0x68, 0x75, 0xd7, 0xa2, 0xef, 0x53, 0x95,
	0xaf, 0x20, 0x17, 0x44, 0xe2, 0xe2, 0xce, 0x38, 0x49, 0x97, 0x4e, 0x56, 0x30, 0x6d, 0x08, 0xa5,
	0x3d, 0x05, 0x6f, 0x4b, 0xb8, 0x0e, 0x27, 0xd7, 0xf4, 0xfd, 0x62, 0xd2, 0x7e, 0x17, 0xa0, 0xb4,
	0x47, 0xf8, 0x26, 0x89, 0xff, 0x23, 0x4d, 0x21, 0x64, 0x3b, 0x74, 0x69, 0xcf, 0x68, 0xea, 0x44,
	0x22, 0x90, 0x9e, 0xcc, 0x9f, 0x78, 0x0b, 0xc9, 0x84, 0x99, 0xfc, 0xc6, 0x76, 0xe2, 0xd1, 0x67,
	0x26, 0x2e, 0x82, 0x68, 0x5b, 0x7c, 0xee, 0xf3, 0x44, 0xb4, 0xf9, 0x76, 0xf0, 0xcc, 0xf0, 0x41,
	0x55, 0x22, 0x1e, 0x66, 0x33, 0xcc, 0x72, 0xae, 0x66, 0x23, 0xcc, 0x72, 0xae, 0xfd, 0x21, 0xc0,
	0x21, 0x9b, 0x86, 0xc9, 0xfb, 0xcf, 0xea, 0x17, 0x90, 0xb5, 0x78, 0x40, 0x5c, 0x63, 0xa1, 0x71,
	0x9c, 0x60, 0x8a, 0xa2, 0x25, 0x31, 0x48, 0xfb, 0x0e, 0x8e, 0x62, 0x21, 0x6f, 0xca, 0x7c, 0x6d,
	0x06, 0xf9, 0xf5, 0x46, 0xc6, 0x59, 0x10, 0x8d, 0x5b, 0x94, 0xc1, 0x05, 0xc8, 0xdd, 0xe9, 0xb7,
	0xba, 0xf1, 0xbd, 0x8e, 0x04, 0x76, 0xd0, 0x8d, 0xa9, 0x6e, 0x74, 0xba, 0x48, 0xc4, 0x79, 0x50,
	0x74, 0x63, 0x3a, 0x9c, 0x20, 0x09, 0x63, 0x28, 0xf6, 0xf4, 0x71, 0x97, 0xe8, 0xcd, 0xfe, 0xb4,
	0x4b, 0x88, 0x41, 0x90, 0x8c, 0x8f, 0xe1, 0xc3, 0x9e, 0x3e, 0x69, 0xf6, 0x7b, 0x9d, 0xe9, 0xb0,
	0x49, 0x9a, 0x83, 0xee, 0xb8, 0x4b, 0x90, 0x52, 0xbb, 0x80, 0xc2, 0xd6, 0x86, 0x66, 0x8c, 0xa3,
	0xb1, 0x41, 0x9a, 0xd7, 0x5d, 0x94, 0x61, 0x8c, 0xfd, 0xde, 0xa0, 0x37, 0x46, 0x42, 0xed, 0x12,
	0x64, 0xb6, 0x70, 0xb1, 0x02, 0x42, 0x0b, 0x65, 0x98, 0x9a, 0xdb, 0x16, 0x12, 0xd8, 0x77, 0xd0,
	0x42, 0x22, 0xfb, 0x5e, 0xb7, 0x90, 0xc4, 0x9e, 0xdb, 0x48, 0xae, 0x7d, 0x0e, 0x87, 0xdb, 0x73,
	0x8f, 0x73, 0x20, 0xdd, 0x74, 0x3a, 0x28, 0xc3, 0x8c, 0xd1, 0xa8, 0x83, 0x04, 0x66, 0xe8, 0x93,
	0x01, 0x12, 0x1b, 0xff, 0x88, 0x50, 0x68, 0x6f, 0xb2, 0x81, 0x7f, 0x80, 0xe2, 0xee, 0x4e, 0xc3,
	0xe7, 0xc9, 0xf5, 0x97, 0xb6, 0x99, 0xcb, 0x17, 0x2f, 0xa0, 0xe2, 0x52, 0xfc, 0x08, 0x1f, 0x24,
	0xe6, 0x03, 0x27, 0x7f, 0x99, 0x3e, 0x90, 0xe5, 0x4f, 0x5f, 0x82, 0x6d, 0x3c, 0x24, 0x96, 0x04,
	0x4e, 0xd1, 0xf6, 0x1a, 0x0f, 0xff, 0xb5, 0x6b, 0x5a, 0xa0, 0xf0, 0xfe, 0xc2, 0xa7, 0x29, 0x31,
	0xaf, 0xda, 0xbf, 0x7c, 0x96, 0xfe, 0x18, 0x71, 0xdc, 0x67, 0xf9, 0x1f, 0x95, 0xab, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x07, 0xd3, 0xab, 0xc3, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	// scheduler -> coordinator
	PutPodResource(ctx context.Context, in *PutPodResourceRequest, opts ...grpc.CallOption) (*PutPodResourceResponse, error)
	// scheduler -> coordinator
	GetNodeResource(ctx context.Context, in *GetNodeResourceRequest, opts ...grpc.CallOption) (*GetNodeResourceResponse, error)
	// executor -> coordinator
	PutNodeResource(ctx context.Context, in *PutNodeResourceRequest, opts ...grpc.CallOption) (*PutNodeResourceResponse, error)
	// executor -> coordinator
	PutPV(ctx context.Context, in *PutPVRequest, opts ...grpc.CallOption) (*PutPVResponse, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) PutPodResource(ctx context.Context, in *PutPodResourceRequest, opts ...grpc.CallOption) (*PutPodResourceResponse, error) {
	out := new(PutPodResourceResponse)
	err := c.cc.Invoke(ctx, "/coordinatorpb.Coordinator/PutPodResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetNodeResource(ctx context.Context, in *GetNodeResourceRequest, opts ...grpc.CallOption) (*GetNodeResourceResponse, error) {
	out := new(GetNodeResourceResponse)
	err := c.cc.Invoke(ctx, "/coordinatorpb.Coordinator/GetNodeResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutNodeResource(ctx context.Context, in *PutNodeResourceRequest, opts ...grpc.CallOption) (*PutNodeResourceResponse, error) {
	out := new(PutNodeResourceResponse)
	err := c.cc.Invoke(ctx, "/coordinatorpb.Coordinator/PutNodeResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutPV(ctx context.Context, in *PutPVRequest, opts ...grpc.CallOption) (*PutPVResponse, error) {
	out := new(PutPVResponse)
	err := c.cc.Invoke(ctx, "/coordinatorpb.Coordinator/PutPV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	// scheduler -> coordinator
	PutPodResource(context.Context, *PutPodResourceRequest) (*PutPodResourceResponse, error)
	// scheduler -> coordinator
	GetNodeResource(context.Context, *GetNodeResourceRequest) (*GetNodeResourceResponse, error)
	// executor -> coordinator
	PutNodeResource(context.Context, *PutNodeResourceRequest) (*PutNodeResourceResponse, error)
	// executor -> coordinator
	PutPV(context.Context, *PutPVRequest) (*PutPVResponse, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) PutPodResource(ctx context.Context, req *PutPodResourceRequest) (*PutPodResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPodResource not implemented")
}
func (*UnimplementedCoordinatorServer) GetNodeResource(ctx context.Context, req *GetNodeResourceRequest) (*GetNodeResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeResource not implemented")
}
func (*UnimplementedCoordinatorServer) PutNodeResource(ctx context.Context, req *PutNodeResourceRequest) (*PutNodeResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutNodeResource not implemented")
}
func (*UnimplementedCoordinatorServer) PutPV(ctx context.Context, req *PutPVRequest) (*PutPVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPV not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_PutPodResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPodResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutPodResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordinatorpb.Coordinator/PutPodResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutPodResource(ctx, req.(*PutPodResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetNodeResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetNodeResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordinatorpb.Coordinator/GetNodeResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetNodeResource(ctx, req.(*GetNodeResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutNodeResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNodeResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutNodeResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordinatorpb.Coordinator/PutNodeResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutNodeResource(ctx, req.(*PutNodeResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutPV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutPV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordinatorpb.Coordinator/PutPV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutPV(ctx, req.(*PutPVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coordinatorpb.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutPodResource",
			Handler:    _Coordinator_PutPodResource_Handler,
		},
		{
			MethodName: "GetNodeResource",
			Handler:    _Coordinator_GetNodeResource_Handler,
		},
		{
			MethodName: "PutNodeResource",
			Handler:    _Coordinator_PutNodeResource_Handler,
		},
		{
			MethodName: "PutPV",
			Handler:    _Coordinator_PutPV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coordinator.proto",
}
